'use client';

import { useState } from 'react';

interface ContentPackage {
  youtubeTitles?: string[];
  hooks?: string[];
  twitterThread?: string;
  linkedinPost?: string;
  thumbnailIdeas?: string[];
  ctaVariations?: string[];
  fullScript?: string;
  shortFormScripts?: string[];
}

interface ExportModalProps {
  idea: string;
  content: ContentPackage;
  onClose: () => void;
}

export default function ExportModal({ idea, content, onClose }: ExportModalProps) {
  const [exporting, setExporting] = useState(false);
  const [exported, setExported] = useState(false);

  const exportToPDF = async () => {
    setExporting(true);
    try {
      // Dynamically import to avoid SSR issues
      const jsPDF = (await import('jspdf')).default;
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 15;
      const maxWidth = pageWidth - margin * 2;
      let y = 20;

      const addText = (text: string, size = 10, bold = false, color = [30, 30, 50] as [number, number, number]) => {
        doc.setFontSize(size);
        doc.setFont('helvetica', bold ? 'bold' : 'normal');
        doc.setTextColor(...color);
        const lines = doc.splitTextToSize(text, maxWidth);
        if (y + lines.length * (size * 0.4) > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(lines, margin, y);
        y += lines.length * (size * 0.45) + 3;
      };

      const addSection = (title: string) => {
        y += 4;
        if (y > 260) { doc.addPage(); y = 20; }
        doc.setFillColor(79, 70, 229);
        doc.roundedRect(margin, y - 4, maxWidth, 8, 2, 2, 'F');
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255, 255, 255);
        doc.text(title.toUpperCase(), margin + 3, y + 1);
        y += 9;
      };

      const addDivider = () => {
        doc.setDrawColor(200, 200, 220);
        doc.line(margin, y, pageWidth - margin, y);
        y += 5;
      };

      // Header
      doc.setFillColor(15, 15, 25);
      doc.rect(0, 0, pageWidth, 35, 'F');
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.text('Content Package', margin, 15);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(180, 180, 200);
      doc.text(`Generated by ContentAgent AI  •  ${new Date().toLocaleDateString()}`, margin, 22);
      y = 40;

      // Idea
      addText('CONTENT IDEA', 9, true, [100, 100, 130]);
      addText(idea, 11, false, [30, 30, 60]);
      addDivider();

      // YouTube Titles
      if (content.youtubeTitles && content.youtubeTitles.length > 0) {
        addSection('🎬 YouTube Titles');
        content.youtubeTitles.slice(0, 8).forEach((title, i) => {
          addText(`${i + 1}. ${title}`, 10);
        });
      }

      // Hooks
      if (content.hooks && content.hooks.length > 0) {
        addSection('⚡ Video Hooks');
        content.hooks.forEach((hook, i) => {
          addText(`${i + 1}. ${hook}`, 10);
        });
      }

      // Twitter Thread
      if (content.twitterThread) {
        addSection('🐦 Twitter / X Thread');
        addText(content.twitterThread, 9.5);
      }

      // LinkedIn Post
      if (content.linkedinPost) {
        addSection('💼 LinkedIn Post');
        addText(content.linkedinPost, 9.5);
      }

      // Thumbnail Ideas
      if (content.thumbnailIdeas && content.thumbnailIdeas.length > 0) {
        addSection('🖼 Thumbnail Ideas');
        content.thumbnailIdeas.forEach((t, i) => {
          addText(`${i + 1}. ${t}`, 10);
        });
      }

      // CTAs
      if (content.ctaVariations && content.ctaVariations.length > 0) {
        addSection('📣 Call-to-Action Variations');
        content.ctaVariations.forEach((cta, i) => {
          addText(`${i + 1}. ${cta}`, 10);
        });
      }

      // Full Script
      if (content.fullScript) {
        addSection('📜 Full YouTube Script');
        addText(content.fullScript, 9);
      }

      // Short Form Scripts
      if (content.shortFormScripts && content.shortFormScripts.length > 0) {
        addSection('📱 Short Form Scripts (Reels/TikTok)');
        content.shortFormScripts.forEach((script, i) => {
          addText(`Script ${i + 1}:`, 10, true);
          addText(script, 9);
          y += 2;
        });
      }

      // Footer
      const totalPages = (doc.internal as any).getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(150, 150, 170);
        doc.text(`Page ${i} of ${totalPages}  •  ContentAgent AI`, margin, 290);
      }

      const filename = `content-package-${idea.substring(0, 30).replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`;
      doc.save(filename);
      setExported(true);
      setTimeout(() => setExported(false), 3000);
    } catch (error) {
      console.error('PDF export failed:', error);
      alert('PDF export failed. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  const sections = [
    { label: 'YouTube Titles', count: content.youtubeTitles?.length },
    { label: 'Video Hooks', count: content.hooks?.length },
    { label: 'Twitter Thread', count: content.twitterThread ? 1 : 0 },
    { label: 'LinkedIn Post', count: content.linkedinPost ? 1 : 0 },
    { label: 'Thumbnail Ideas', count: content.thumbnailIdeas?.length },
    { label: 'CTA Variations', count: content.ctaVariations?.length },
    { label: 'Full Script', count: content.fullScript ? 1 : 0 },
    { label: 'Short Form Scripts', count: content.shortFormScripts?.length },
  ].filter(s => s.count && s.count > 0);

  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center',
      background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(8px)'
    }}>
      <div style={{
        background: 'linear-gradient(135deg, #0f0f1a 0%, #1a1a2e 100%)',
        border: '1px solid rgba(79,70,229,0.3)',
        borderRadius: '16px',
        padding: '32px',
        width: '480px',
        maxWidth: '90vw',
        boxShadow: '0 25px 50px rgba(0,0,0,0.5), 0 0 0 1px rgba(79,70,229,0.2)'
      }}>
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
          <div>
            <h2 style={{ margin: 0, color: '#fff', fontSize: '20px', fontWeight: 700 }}>📄 Export Content</h2>
            <p style={{ margin: '4px 0 0', color: '#9090b0', fontSize: '13px' }}>Download as a formatted PDF</p>
          </div>
          <button onClick={onClose} style={{
            background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)',
            color: '#aaa', borderRadius: '8px', padding: '6px 10px', cursor: 'pointer', fontSize: '16px'
          }}>✕</button>
        </div>

        {/* What's Included */}
        <div style={{
          background: 'rgba(79,70,229,0.08)', border: '1px solid rgba(79,70,229,0.2)',
          borderRadius: '12px', padding: '16px', marginBottom: '24px'
        }}>
          <p className="text-xs text-gray-400 font-semibold uppercase tracking-wider mb-3">
            ✅ What&apos;s Included
          </p>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
            {sections.map(s => (
              <span key={s.label} style={{
                background: 'rgba(79,70,229,0.15)', border: '1px solid rgba(79,70,229,0.3)',
                color: '#a0a0e0', borderRadius: '6px', padding: '3px 10px', fontSize: '12px'
              }}>
                {s.label} {s.count && s.count > 1 ? `(${s.count})` : ''}
              </span>
            ))}
          </div>
        </div>

        {/* Buttons */}
        <div style={{ display: 'flex', gap: '12px' }}>
          <button onClick={onClose} style={{
            flex: 1, padding: '12px', borderRadius: '10px', border: '1px solid rgba(255,255,255,0.1)',
            background: 'transparent', color: '#888', cursor: 'pointer', fontSize: '14px'
          }}>Cancel</button>
          <button
            onClick={exportToPDF}
            disabled={exporting}
            style={{
              flex: 2, padding: '12px', borderRadius: '10px', border: 'none',
              background: exported ? 'linear-gradient(135deg, #10b981, #059669)' : 'linear-gradient(135deg, #4f46e5, #7c3aed)',
              color: '#fff', cursor: exporting ? 'not-allowed' : 'pointer', fontSize: '14px',
              fontWeight: 700, transition: 'all 0.3s', opacity: exporting ? 0.7 : 1,
              boxShadow: '0 4px 15px rgba(79,70,229,0.4)'
            }}
          >
            {exporting ? '⏳ Generating PDF...' : exported ? '✅ Downloaded!' : '📥 Download PDF'}
          </button>
        </div>
      </div>
    </div>
  );
}
