import { ContentPackage } from '../types';
import { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, Packer } from 'docx';

/**
 * Export Service
 * Handles generation of downloadable files from content packages
 */
export class ExportService {
  /**
   * Generate plain text export with all content sections
   * @param content - The content package to export
   * @param idea - The original content idea
   * @returns Formatted plain text string
   */
  generateTxt(content: ContentPackage, idea: string): string {
    const timestamp = new Date().toISOString();
    
    const sections = [
      'CONTENT EXECUTION AGENT - GENERATED CONTENT',
      `Original Idea: ${idea}`,
      `Generated: ${timestamp}`,
      '',
      '='.repeat(60),
      '',
      '=== YOUTUBE TITLES ===',
      '',
      ...content.youtubeTitles.map((title, i) => `${i + 1}. ${title}`),
      '',
      '=== HOOKS ===',
      '',
      ...content.hooks.map((hook, i) => `Hook ${i + 1}:\n${hook}\n`),
      '',
      '=== FULL SCRIPT ===',
      '',
      content.fullScript,
      '',
      '=== SHORT-FORM SCRIPTS ===',
      '',
      ...content.shortFormScripts.map((script, i) => `Script ${i + 1}:\n${script}\n`),
      '',
      '=== TWITTER/X THREAD ===',
      '',
      content.twitterThread,
      '',
      '=== LINKEDIN POST ===',
      '',
      content.linkedinPost,
      '',
      '=== THUMBNAIL IDEAS ===',
      '',
      ...content.thumbnailIdeas.map((idea, i) => `${i + 1}. ${idea}`),
      '',
      '=== CTA VARIATIONS ===',
      '',
      ...content.ctaVariations.map((cta, i) => `${i + 1}. ${cta}`),
      '',
      '='.repeat(60),
      '',
      'Generated by Content Execution Agent',
    ];
    
    return sections.join('\n');
  }

  /**
   * Generate Word document export with formatted sections
   * @param content - The content package to export
   * @param idea - The original content idea
   * @returns Buffer containing the .docx file
   */
  async generateDoc(content: ContentPackage, idea: string): Promise<Buffer> {
    const timestamp = new Date().toLocaleString();
    
    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          // Title
          new Paragraph({
            text: 'CONTENT EXECUTION AGENT',
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
          }),
          
          // Metadata
          new Paragraph({
            children: [
              new TextRun({ text: 'Original Idea: ', bold: true }),
              new TextRun(idea),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: 'Generated: ', bold: true }),
              new TextRun(timestamp),
            ],
            spacing: { after: 400 },
          }),
          
          // YouTube Titles
          new Paragraph({
            text: 'YouTube Titles',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 200, after: 200 },
          }),
          ...content.youtubeTitles.map((title, i) => 
            new Paragraph({
              text: `${i + 1}. ${title}`,
              spacing: { after: 100 },
            })
          ),
          
          // Hooks
          new Paragraph({
            text: 'Hooks',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
          ...content.hooks.flatMap((hook, i) => [
            new Paragraph({
              text: `Hook ${i + 1}`,
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 200, after: 100 },
            }),
            new Paragraph({
              text: hook,
              spacing: { after: 200 },
            }),
          ]),
          
          // Full Script
          new Paragraph({
            text: 'Full Script',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
          ...this.parseMarkdownToParagraphs(content.fullScript),
          
          // Short-Form Scripts
          new Paragraph({
            text: 'Short-Form Scripts',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
          ...content.shortFormScripts.flatMap((script, i) => [
            new Paragraph({
              text: `Script ${i + 1}`,
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 200, after: 100 },
            }),
            ...this.parseMarkdownToParagraphs(script),
          ]),
          
          // Twitter Thread
          new Paragraph({
            text: 'Twitter/X Thread',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
          ...this.parseMarkdownToParagraphs(content.twitterThread),
          
          // LinkedIn Post
          new Paragraph({
            text: 'LinkedIn Post',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
          ...this.parseMarkdownToParagraphs(content.linkedinPost),
          
          // Thumbnail Ideas
          new Paragraph({
            text: 'Thumbnail Ideas',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
          ...content.thumbnailIdeas.map((idea, i) => 
            new Paragraph({
              text: `${i + 1}. ${idea}`,
              spacing: { after: 100 },
            })
          ),
          
          // CTA Variations
          new Paragraph({
            text: 'CTA Variations',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
          ...content.ctaVariations.map((cta, i) => 
            new Paragraph({
              text: `${i + 1}. ${cta}`,
              spacing: { after: 100 },
            })
          ),
          
          // Footer
          new Paragraph({
            children: [
              new TextRun({
                text: 'Generated by Content Execution Agent',
                italics: true,
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { before: 600 },
          }),
        ],
      }],
    });
    
    return await Packer.toBuffer(doc);
  }

  /**
   * Generate a safe filename from the content idea and timestamp
   * @param idea - The original content idea
   * @param extension - File extension (e.g., 'txt', 'docx')
   * @returns Sanitized filename
   */
  generateFilename(idea: string, extension: string): string {
    const timestamp = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
    
    // Sanitize the idea for use in filename
    const sanitizedIdea = this.sanitizeFilename(idea);
    
    // Truncate to reasonable length (50 chars) and add timestamp
    const truncatedIdea = sanitizedIdea.substring(0, 50);
    
    return `content-${timestamp}-${truncatedIdea}.${extension}`;
  }

  /**
   * Sanitize a string for safe use in filenames
   * @param input - The string to sanitize
   * @returns Sanitized string safe for filenames
   */
  private sanitizeFilename(input: string): string {
    return input
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-') // Replace non-alphanumeric with hyphens
      .replace(/^-+|-+$/g, '')     // Remove leading/trailing hyphens
      .replace(/-+/g, '-')          // Collapse multiple hyphens
      || 'content';                 // Fallback if empty
  }

  /**
   * Parse markdown text into Word document paragraphs
   * Handles basic markdown: headings, bold, lists
   * @param text - Markdown text to parse
   * @returns Array of Paragraph objects
   */
  private parseMarkdownToParagraphs(text: string): Paragraph[] {
    const lines = text.split('\n');
    const paragraphs: Paragraph[] = [];
    
    for (const line of lines) {
      if (!line.trim()) {
        // Empty line - add spacing
        paragraphs.push(new Paragraph({ text: '', spacing: { after: 100 } }));
        continue;
      }
      
      // Check for markdown heading
      if (line.startsWith('### ')) {
        paragraphs.push(new Paragraph({
          text: line.substring(4),
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 200, after: 100 },
        }));
      } else if (line.startsWith('## ')) {
        paragraphs.push(new Paragraph({
          text: line.substring(3),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 150 },
        }));
      } else if (line.startsWith('# ')) {
        paragraphs.push(new Paragraph({
          text: line.substring(2),
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        }));
      } else if (line.match(/^[\*\-]\s/)) {
        // Bullet point
        paragraphs.push(new Paragraph({
          text: line.substring(2),
          bullet: { level: 0 },
          spacing: { after: 50 },
        }));
      } else if (line.match(/^\d+\.\s/)) {
        // Numbered list
        paragraphs.push(new Paragraph({
          text: line.replace(/^\d+\.\s/, ''),
          numbering: { reference: 'default-numbering', level: 0 },
          spacing: { after: 50 },
        }));
      } else {
        // Regular paragraph - handle bold text
        const children = this.parseInlineMarkdown(line);
        paragraphs.push(new Paragraph({
          children,
          spacing: { after: 150 },
        }));
      }
    }
    
    return paragraphs;
  }

  /**
   * Parse inline markdown (bold, italic) into TextRun objects
   * @param text - Text with inline markdown
   * @returns Array of TextRun objects
   */
  private parseInlineMarkdown(text: string): TextRun[] {
    const runs: TextRun[] = [];
    const boldRegex = /\*\*(.+?)\*\*/g;
    let lastIndex = 0;
    let match;
    
    while ((match = boldRegex.exec(text)) !== null) {
      // Add text before bold
      if (match.index > lastIndex) {
        runs.push(new TextRun(text.substring(lastIndex, match.index)));
      }
      
      // Add bold text
      runs.push(new TextRun({ text: match[1], bold: true }));
      lastIndex = match.index + match[0].length;
    }
    
    // Add remaining text
    if (lastIndex < text.length) {
      runs.push(new TextRun(text.substring(lastIndex)));
    }
    
    // If no markdown found, return single run
    return runs.length > 0 ? runs : [new TextRun(text)];
  }
}

// Export singleton instance
export const exportService = new ExportService();
